from tkinter import *
from tkinter.ttk import *
root=Tk()
root.title("The marvellous APUSH Game")
root.geometry("10000x10000")

f1 = Frame(root)
f1.pack()

#THe pIcs place
pic1 = PhotoImage(file = "APUSH Sucks.png")
pic2 = PhotoImage(file = "Sleep it off.png")
pic3 = PhotoImage(file = "Talking to the brain.png")
pic4 = PhotoImage(file = "Brain shows columbus to the character.png")
pic5 = PhotoImage(file = "Note_1 pic.png")
pic6 = PhotoImage(file = "Treaty of Tordesillas.png")
pic7 = PhotoImage(file = "Note_3 pic.png")
pic8 = PhotoImage(file = "pic8.png")
pic9 = PhotoImage(file = "pic9.png")
pic10 = PhotoImage(file = "pic10.png")
pic11 = PhotoImage(file = "pic11.png")
pic12 = PhotoImage(file = "pic12.png")
pic13 = PhotoImage(file = "pic13.png")
pic14 = PhotoImage(file = "pic14.png")
pic15 = PhotoImage(file = "pic15.png")
pic16 = PhotoImage(file = "pic16.png")
pic17 = PhotoImage(file = "pic17.png")
pic18 = PhotoImage(file = "pic18.png")
pic19 = PhotoImage(file = "pic19.png")
pic20 = PhotoImage(file = "pic20.png")
pic21 = PhotoImage(file = "pic21.png")
pic22 = PhotoImage(file = "pic22.png")
pic23 = PhotoImage(file = "pic23.png")
pic24 = PhotoImage(file = "pic24.png")
pic25 = PhotoImage(file = "pic25.png")
pic26 = PhotoImage(file = "pic26.png")
pic27 = PhotoImage(file = "pic27.png")
pic28 = PhotoImage(file = "pic28.png")
pic29 = PhotoImage(file = "pic29.png")
pic30 = PhotoImage(file = "pic30.png")
pic31 = PhotoImage(file = "pic31.png")
pic32 = PhotoImage(file = "pic32.png")
pic33 = PhotoImage(file = "pic33.png")
pic34 = PhotoImage(file = "pic34.png")
pic35 = PhotoImage(file = "pic35.png")
pic36 = PhotoImage(file = "pic36.png")
pic37 = PhotoImage(file = "pic37.png")
pic38 = PhotoImage(file = "pic38.png")
pic39 = PhotoImage(file = "pic39.png")
pic40 = PhotoImage(file = "pic40.png")
pic41 = PhotoImage(file = "pic41.png")
pic42 = PhotoImage(file = "pic42.png")
pic43 = PhotoImage(file = "pic43.png")
pic44 = PhotoImage(file = "pic44.png")
pic45 = PhotoImage(file = "pic45.png")
pic46 = PhotoImage(file = "pic46.png")
pic47 = PhotoImage(file = "pic47.png")
pic48 = PhotoImage(file = "pic48.png")
pic49 = PhotoImage(file = "pic49.png")
pic50 = PhotoImage(file = "pic50.png")
pic51 = PhotoImage(file = "pic51.png")
pic52 = PhotoImage(file = "pic52.png")
pic53 = PhotoImage(file = "pic53.png")
pic54=  PhotoImage(file = "pic54.png")
pic55 = PhotoImage(file = "pic55.png")
pic56 = PhotoImage(file = "pic56.png")
pic57 = PhotoImage(file = "pic57.png")
pic58 = PhotoImage(file = "pic58.png")
pic59 = PhotoImage(file = "pic59.png")
pic60 = PhotoImage(file = "pic60.png")
pic61 = PhotoImage(file = "pic61.png")
pic62 = PhotoImage(file = "pic62.png")
pic63 = PhotoImage(file = "pic63.png")
pic64 = PhotoImage(file = "pic64.png")
pic65 = PhotoImage(file = "pic65.png")
pic66 = PhotoImage(file = "pic66.png")
pic67 = PhotoImage(file = "pic67.png")
pic68 = PhotoImage(file = "pic68.png")
"""
pic69 = PhotoImage(file = "pic40.png")
pic70 = PhotoImage(file = "pic41.png")
pic71 = PhotoImage(file = "pic40.png")
pic72 = PhotoImage(file = "pic41.png")
pic73 = PhotoImage(file = "pic40.png")
pic74 = PhotoImage(file = "pic41.png")
pic75 = PhotoImage(file = "pic40.png")
pic76 = PhotoImage(file = "pic41.png")




"""
#The infinite COmmandments
def ikr():
	f1.destroy()
	f2.pack()
def sleep():
	f2.destroy()
	f3.pack()
def talk_to_brain():
	l6 = Label(f3, text="Hey brain, you're smart help me with APUSH",font=('Arial', 13))
	l6.grid(row = 5, column =2)
	l7 = Label(f3, text="                                                               No, study by yourself",font=('Arial', 13))
	l7.grid(row = 6, column =2)
	l8 = Label(f3, text="I'll make sure to play 12 hours of COD if we get an 'A' on the test",font=('Arial', 13))
	l8.grid(row = 7, column =2)
	l9 = Label(f3, text="                                                                Deal",font=('Arial', 13))
	l9.grid(row = 8, column =2)
	btn4 = Button(f3, text = "TEACH ME HISTORY", command=Unit_1)
	btn4.grid(row = 9,column=2)
def Unit_1():
	f3.destroy()
	f4.pack()
def notes_1():
	f4.destroy()
	f5.pack()
def notes_2():
	f5.destroy()
	f6.pack()
def notes_3():
	f6.destroy()
	f7.pack()
def notes_4():
	f7.destroy()
	f8.pack()
def notes_5():
	f8.destroy()
	f9.pack()
def Unit_2():
	f9.destroy()
	f10.pack()
def notes_6():
	f10.destroy()
	f11.pack()
def notes_7():
	f11.destroy()
	f12.pack()
def notes_8():
	f12.destroy()
	f13.pack()
def notes_9():
	f13.destroy()
	f14.pack()
def notes_10():
	f14.destroy()
	f15.pack()
def notes_11():
	f15.destroy()
	f16.pack()
def notes_12():
	f16.destroy()
	f17.pack()
def notes_13():
	f17.destroy()
	f18.pack()
def notes_14():
	f18.destroy()
	f19.pack()
def notes_15():
	f19.destroy()
	f20.pack()
def notes_16():
	f20.destroy()
	f21.pack()
def notes_17():
	f21.destroy()
	f22.pack()
def notes_18():
	f22.destroy()
	f23.pack()
def notes_19():
	f23.destroy()
	f24.pack()
def notes_20():
	f24.destroy()
	f25.pack()
def notes_21():
	f25.destroy()
	f26.pack()
def notes_22():
	f26.destroy()
	f27.pack()
def notes_23():
	f27.destroy()
	f28.pack()
def notes_24():
	f28.destroy()
	f29.pack()
def notes_25():
	f29.destroy()
	f30.pack()
def notes_26():
	f30.destroy()
	f31.pack()
def notes_27():
	f31.destroy()
	f32.pack()
def notes_28():
	f32.destroy()
	f33.pack()
def notes_29():
	f33.destroy()
	f34.pack()
def notes_30():
	f34.destroy()
	f35.pack()
def notes_31():
	f35.destroy()
	f36.pack()
def notes_32():
	f36.destroy()
	f37.pack()
def notes_33():
	f37.destroy()
	f38.pack()
def notes_34():
	f38.destroy()
	f39.pack()
def notes_35():
	f39.destroy()
	f40.pack()
def notes_36():
	f40.destroy()
	f41.pack()
def notes_37():
	f41.destroy()
	f42.pack()
def notes_38():
	f42.destroy()
	f43.pack()
def notes_39():
	f43.destroy()
	f44.pack()
def notes_40():
	f44.destroy()
	f45.pack()
def notes_41():
	f45.destroy()
	f46.pack()
def notes_42():
	f46.destroy()
	f47.pack()
def notes_43():
	f47.destroy()
	f48.pack()
def notes_44():
	f48.destroy()
	f49.pack()
def notes_45():
	f49.destroy()
	f50.pack()
def notes_46():
	f50.destroy()
	f51.pack()
def notes_47():
	f51.destroy()
	f52.pack()
def notes_48():
	f52.destroy()
	f53.pack()
def notes_49():
	f53.destroy()
	f54.pack()
def notes_50():
	f54.destroy()
	f55.pack()
def notes_51():
	f55.destroy()
	f56.pack()
def notes_52():
	f56.destroy()
	f57.pack()
def notes_53():
	f57.destroy()
	f58.pack()
def notes_54():
	f58.destroy()
	f59.pack()
def notes_55():
	f59.destroy()
	f60.pack()
def notes_56():
	f60.destroy()
	f61.pack()
def notes_57():
	f61.destroy()
	f62.pack()
def notes_58():
	f62.destroy()
	f63.pack()
def notes_59():
	f63.destroy()
	f64.pack()
def notes_60():
	f64.destroy()
	f65.pack()
def notes_61():
	f65.destroy()
	f66.pack()
def notes_62():
	f66.destroy()
	f67.pack()
def notes_63():
	f67.destroy()
	f68.pack()
def notes_64():
	f68.destroy()
	f69.pack()
def notes_65():
	f69.destroy()
	f70.pack()
def notes_66():
	f70.destroy()
	f71.pack()
def notes_67():
	f71.destroy()
	f72.pack()
def notes_68():
	f72.destroy()
	f73.pack()
def notes_69():
	f73.destroy()
	f74.pack()
def notes_70():
	f74.destroy()
	f75.pack()
def notes_71():
	f75.destroy()
	f76.pack()	
def notes_72():
	f76.destroy()
	f77.pack()
def notes_73():
	f77.destroy()
	f78.pack()
def notes_74():
	f78.destroy()
	f79.pack()
def notes_75():
	f79.destroy()
	f80.pack()
def notes_76():
	f80.destroy()
	f81.pack()
def notes_77():
	f81.destroy()
	f82.pack()
def notes_78():
	f82.destroy()
	f83.pack()
def notes_79():
	f83.destroy()
	f84.pack()
def notes_80():
	f84.destroy()
	f85.pack()
def notes_81():
	f85.destroy()
	f86.pack()
def notes_82():
	f86.destroy()
	f87.pack()
def notes_83():
	f87.destroy()
	f88.pack()
def notes_84():
	f88.destroy()
	f89.pack()
def notes_85():
	f89.destroy()
	f90.pack()	
def notes_86():
	f90.destroy()
	f91.pack()
def notes_87():
	f91.destroy()
	f92.pack()
def notes_88():
	f92.destroy()
	f93.pack()
def notes_89():
	f93.destroy()
	f94.pack()
def notes_90():
	f94.destroy()
	f95.pack()
def notes_91():
	f95.destroy()
	f96.pack()
def notes_92():
	f96.destroy()
	f97.pack()
def notes_93():
	f97.destroy()
	f98.pack()
def notes_94():
	f98.destroy()
	f99.pack()
def notes_95():
	f99.destroy()
	f100.pack()
def notes_96():
	f100.destroy()
	f101.pack()
def notes_97():
	f101.destroy()
	f102.pack()
def notes_98():
	f102.destroy()
	f103.pack()
def notes_99():
	f103.destroy()
	f104.pack()
def notes_100():
	f104.destroy()
	f105.pack()
def notes_101():
	f105.destroy()
	f106.pack()
def notes_102():
	f106.destroy()
	f107.pack()
def notes_103():
	f107.destroy()
	f108.pack()
def notes_104():
	f108.destroy()
	f109.pack()
def notes_105():
	f109.destroy()
	f110.pack()
def notes_106():
	f110.destroy()
	f111.pack()
def notes_107():
	f111.destroy()
	f112.pack()
def notes_108():
	f112.destroy()
	f113.pack()
def notes_109():
	f113.destroy()
	f114.pack()
def notes_110():
	f114.destroy()
	f115.pack()
def notes_111():
	f115.destroy()
	f116.pack()
def notes_112():
	f116.destroy()
	f117.pack()
def notes_113():
	f117.destroy()
	f118.pack()
def notes_114():
	f118.destroy()
	f119.pack()
def notes_115():
	f119.destroy()
	f120.pack()
def notes_116():
	f120.destroy()
	f121.pack()
def notes_117():
	f121.destroy()
	f122.pack()
def notes_118():
	f122.destroy()
	f123.pack()
def notes_119():
	f123.destroy()
	f124.pack()



#Gameplay
l2 = Label(f1,image=pic1)
l2.grid(row = 3,column=2)
l1 = Label(f1, text="Man, APUSH Sucks why am I doing this",font=('Arial', 13))
l1.grid(row=4, column=2)
btn1=Button(f1, text="I know right!", command=ikr)
btn1.grid(row=5, column=2)

f2=Frame(root)
l3 = Label(f2,image=pic2)
l3.grid(row=3, column =2)
l4 = Label(f2, text="Sleep it off, it'll eventually work out",font=('Arial', 13))
l4.grid(row = 4, column =2)
btn2=Button(f2, text="Definitely!", command=sleep)
btn2.grid(row=5, column=2)

f3 = Frame(root)

l5 = Label(f3,image=pic3)
l5.grid(row=3, column =2)
btn3=Button(f3, text="Talk to the brain", command=talk_to_brain)
btn3.grid(row=4, column=2)


f4 = Frame(root)
l9 = Label(f4,image=pic4)
l9.grid(row = 3,column=2)
l10=Label(f4, text="Right now, you're looking at Christopher Columbus arriving to the carribean. The indigenous people do not know it, but they will be enslaved and have their land taken away from them",font=('Arial', 13), wraplength = 400)
l10.grid(row = 8, column =2)
btn4 = Button(f4, text="Well that's a shame", command=notes_1)
btn4.grid(row = 9, column = 2)

f5 = Frame(root)
l11 = Label(f5, text="Here's what you should write down:",font=('Arial', 13))
l11.grid(row = 1, column = 2)
l12 = Label(f5, text="Historians generally recognize three motives for European exploration and colonization in the New World: God, gold, and glory.                               Religious motivations can be traced all the way back to the Crusades, the series of religious wars between the 11th and 15th centuries during which European Christians sought to claim Jerusalem as an exclusively Christian space.                                         Europeans also searched for optimal trade routes to lucrative Asian markets and hoped to gain global recognition for their country.",font=('Arial', 13), wraplength = 400)
l12.grid(row = 2, column = 2)
l9 = Label(f5,image=pic5)
l9.grid(row = 4, column = 2)
l13 = Label(f5, text="Analyze this picture as a bonus:",font=('Arial', 13))
l13.grid(row = 5,column=2)
btn5 = Button(f5, text = "Next please", command = notes_2)
btn5.grid(row = 6,column=2)


f6 = Frame(root)
l11 = Label(f6, image = pic6 )
l11.grid(row = 1, column = 2)
l12 = Label(f6, text="In this picture, you can see the division of land made by the pope in 1494. Spain gets the new world while Portugal gets the old",font=('Arial', 13), wraplength = 400)
l12.grid(row = 2, column = 2)
btn5 = Button(f6, text = "What should I make a note of?", command = notes_3)
btn5.grid(row =5,column=2)

f7= Frame(root)
l12 = Label(f7, text="In the European race to colonial dominance, the Treaty of Tordesillas legitimized Spain’s holdings in the New World, indicating Spanish primacy over Portugal.                                                                   The successes of Columbus ushered in an era of Spanish conquest that led numerous other European explorers to attempt similar colonization projects.                                                                                  Spain gained immense wealth from this expansionism, which translated into an influx of Spanish art and cultural capital.",font=('Arial', 13), wraplength = 400)
l12.grid(row = 2, column = 2)
l11 = Label(f7, image = pic7 )
l11.grid(row = 3, column = 2)
btn5 = Button(f7, text = "Okay, we're making progress", command = notes_4)
btn5.grid(row =5,column=2)

f8 = Frame(root)
l3 = Label(f8,image=pic8)
l3.grid(row=3, column =2)
l4 = Label(f8, text="In this picture, we can see European men fighting against the indigenous people",font=('Arial', 13))
l4.grid(row = 4, column =2)
btn2=Button(f8, text="Damn, Europeans are so greedy", command=notes_5)
btn2.grid(row=5, column=2)

f9= Frame(root)
l4 = Label(f9, text="Now make a note of this: ",font=('Arial', 13))
l4.grid(row = 4, column =2)
l5 = Label(f9, text="Gold, silver, and furs attracted European exploration, colonization, and competition in the New World.                                                                                       Rivalries between European nations were often rooted in religious or political feuds taking place in Europe, yet these tensions played out in the theater of the New World.                                                     The Spanish lost their stronghold in North America as the French, Dutch, and British began to explore and colonize the Northeast. ",font=('Arial', 13), wraplength = 400)
l5.grid(row = 5, column =2)
btn2=Button(f9, text="To unit 2!!", command=Unit_2)
btn2.grid(row=6, column=2)

f10 = Frame(root)
l3 = Label(f10,image=pic9)
l3.grid(row=3, column =2)
l4 = Label(f10, text="In this picture, we can see the first town being set-up",font=('Arial', 13))
l4.grid(row = 4, column =2)
btn2=Button(f10, text="Give me some notes", command=notes_6)
btn2.grid(row=5, column=2)

f11 = Frame(root)
l4 = Label(f11, text="Puritans were English Protestants who were committed to 'purifying' the Church of England by eliminating all aspects of Catholicism from religious practices.                                                             English Puritans founded the colony of Plymouth to practice their own brand of Protestantism without interference.                                                                      New England society was characterized by equality under the law for white male citizens (as demonstrated by the Mayflower Compact), a disciplined work ethic, and a strong maritime economy.",font=('Arial', 13), wraplength = 400)
l4.grid(row = 4, column =2)
btn2=Button(f11, text="Next Please", command=notes_7)
btn2.grid(row=5, column=2)

f12 = Frame(root)
l3 = Label(f12,image=pic10)
l3.grid(row=3, column =2)
l4 = Label(f12, text="This is a map of the Atlantic Ocean",font=('Arial', 13))
l4.grid(row = 4, column =2)
btn2=Button(f12, text="Give me some notes", command=notes_8)
btn2.grid(row=5, column=2)

f13= Frame(root)
l3 = Label(f13, text = "Take notes on these: ", font=('Arial', 13))
l3.grid(row=3, column =2)
l4 = Label(f13, text="During the colonial era, Britain and its colonies engaged in a “triangular trade,” shipping natural resources, goods, and people across the Atlantic Ocean in an effort to enrich the mother country.                                                         Trade with Europeans led to far-reaching consequences among Native American communities, including warfare, cultural change, and disease.                                                             Although the British government attempted to control colonial trade through measures like the Navigation Acts, it only sporadically enforced trade laws.",font=('Arial', 13), wraplength = 400)
l4.grid(row = 4, column =2)
btn2=Button(f13, text="Next topic", command=notes_9)
btn2.grid(row=5, column=2)

f14 = Frame(root)
l3 = Label(f14, image = pic11 )
l3.grid(row=3, column =2)
l4 = Label(f14, text = "This here is the transatlantic slave trade which operated from the 16th to 19th centuries", font=('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f14, text="Next topic", command=notes_10)
btn2.grid(row=5, column=2)

f15 = Frame(root)
l3 = Label(f15, text = "Write or memorize these: ",font = ('Arial', 13) )
l3.grid(row=3, column =2)
l4 = Label(f15, text = "The seventeenth and eighteenth centuries saw the expansion of slavery in the American colonies from South Carolina to Boston.															White colonists' responses to revolts, or even the threat of them, led to gross overreactions and further constraints on enslaved people’s activities.", font=('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f15, text="Next topic", command=notes_11)
btn2.grid(row=5, column=2)

f16 = Frame(root)
l3 = Label(f16, image = pic12 )
l3.grid(row=3, column =2)
l4 = Label(f16, text = "This is a picture a book on enlightenment and spirituality", font=('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f16, text="Next topic", command=notes_12)
btn2.grid(row=5, column=2)

f17 = Frame(root)
l3 = Label(f17, text = "Read this carefully and throughly", font = ('Arial', 13))
l3.grid(row=3, column =2)
l4 = Label(f17, text = "The Great Awakening was an outburst of Protestant Revivalism in the eighteenth century.                                           					The beliefs of the New Lights of the First Great Awakening competed with the more conservative religion of the first colonists, who were known as Old Lights. 																The religious fervor in Great Britain and her North American colonies bound the eighteenth-century British Atlantic together in a shared, common experience. ", font=('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f17, text="Unit 3!!!", command=notes_13)
btn2.grid(row=5, column=2)
 
f18 = Frame(root)
l3 = Label(f18, image = pic13)
l3.grid(row=3, column =2)
l4 = Label(f18, text = "This is an image from the Seven Years War", font=('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f18, text="What's next", command=notes_14)
btn2.grid(row=5, column=2)

f19 = Frame(root)
l3 = Label(f19, text = "Read this", font = ('Arial', 13))
l3.grid(row=3, column =2)
l4 = Label(f19, text = "Conflict between the French and the English over territory, led to a conflict known as the Seven Years’ War. The Seven Years’ War solidified Britain’s stance as the most dominant European country in the world. However, as Britain attempted to increase control on the American colonies, colonists began rebelling, eventually leading to the Revolutionary War.", font=('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f19, text="Next Please", command=notes_15)
btn2.grid(row=5, column=2)

f20 = Frame(root)
l3 = Label(f20, image = pic14)
l3.grid(row=3, column =2)
l4 = Label(f20, text = "This is a picture of the infamous Townshed Act", font=('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f20, text="Tell me more", command=notes_16)
btn2.grid(row=5, column=2)

f21 = Frame(root)
l3 = Label(f21, text = "An Important Topic to learn: ")
l3.grid(row=3, column =2)
l4 = Label(f21, text = "The Townshend Acts, passed in 1767 and 1768, were designed to raise revenue for the British Empire by taxing its North American colonies. They were met with widespread protest in the colonies, especially among merchants in Boston.																	The Townshend Acts renewed a fierce debate over the British Parliament’s right to tax the colonies.																In 1772, Boston revolutionary Samuel Adams urged the creation of a committee of correspondence to communicate with other colonial assemblies, educate townspeople about their political rights, and rally opposition to British rule.", font=('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f21, text="What's next", command=notes_17)
btn2.grid(row=5, column=2)

f22 = Frame(root)
l3 = Label(f22, image = pic15)
l3.grid(row=3, column =2)
l4 = Label(f22, text = "This was a picture of the First Continental Congress", font=('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f22, text="Enumerate on the topic", command=notes_18)
btn2.grid(row=5, column=2)

f23 = Frame(root)
l3 = Label(f23, text = "Facts you must know: ",font=('Arial',13))
l3.grid(row=3, column =2)
l4 = Label(f23, text = "The Second Continental Congress convened in Philadelphia in the summer of 1775, shortly after the war with the British had begun. It was preceded by the First Continental Congress in the fall of 1774.										The Congress appointed George Washington as commander of the Continental Army, and authorized the raising of the army through conscription.														On July 4, 1776, the Congress issued the Declaration of Independence, which for the first time asserted the colonies’ intention to be fully independent of the mother country.															The Congress established itself as the central governing authority under the Articles of Confederation, which remained in force until 1788.", font=('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f23, text="Next topic", command=notes_19)
btn2.grid(row=5, column=2)

f24 = Frame(root)
l3 = Label(f24, image = pic16)
l3.grid(row = 3,column=2)
l4 = Label(f24, text = "This here is the Articles of Confederation", font=('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f24, text="Elucidate on this", command=notes_20)
btn2.grid(row=5, column=2)

f25 = Frame(root)
l3 = Label(f25, text = "Read this", font = ('Arial',13))
l3.grid(row=3, column =2)
l4 = Label(f25, text = "The Articles of Confederation comprised the United States’ first constitution, lasting from 1776 until 1789. The Articles established a weak central government and placed most powers in the hands of the states.											Under the Articles, the US economy faltered, since the central government lacked the power to enforce tax laws or regulate commerce. 														Shays’s Rebellion, an uprising of Revolutionary War veterans in Massachusetts that both the state and national governments struggled to address due to a lack of centralized military power, illustrated the need to create a stronger governing system.", font=('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f25, text="Enumerate on the topic", command=notes_21)
btn2.grid(row=5, column=2)

f26 = Frame(root)
l3 = Label(f26, image = pic18)
l3.grid(row = 3,column=2)
l4 = Label(f26, text = "This here is the U.S. constitution", font=('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f26, text="Elucidate on this", command=notes_22)
btn2.grid(row=5, column=2)

f27 = Frame(root)
l3 = Label(f27, text = "Read this", font = ('Arial',13))
l3.grid(row = 3,column=2)
l4 = Label(f27, text = "The U.S. Constitution, the world's oldest, sets up a three-branch government. The Congress, the most powerful, makes laws. The President enforces them. The Supreme Court interprets them. This system ensures balance, with each branch checking the others. This is the essence of the Constitution's brilliance.", font=('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f27, text="Next topic", command=notes_23)
btn2.grid(row=5, column=2)

f28 = Frame(root)
l3 = Label(f28, image = pic17)
l3.grid(row = 3,column=2)
l4 = Label(f28, text = "This here is the man, the myth, the legend George Washington", font=('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f28, text="This looks interesting, tell me more", command=notes_24)
btn2.grid(row=5, column=2)

f29 = Frame(root)
l3 = Label(f29, text= "Details on George: ", font = ('Arial', 13))
l3.grid(row = 3,column=2)
l4 = Label(f29, text = "Virginian and Revolutionary War General George Washington became the United States's first president in 1789. His actions in office set a precedent for a strong executive branch and a strong central government.																						The major political questions and conflicts during the 1790s concerned foreign policy, economic policy, and the balance of power between states and the federal government.																							During Washington's presidency, factions began to emerge that would soon form the first two political parties in the United States: the Democratic-Republicans and the Federalists.																				Washington’s decision to stay neutral during the French Revolution set a precedent for the United States government to practice isolationism as its main foreign policy strategy for over a hundred years.", font=('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f29, text="Unit 4!!", command=notes_25)
btn2.grid(row=5, column=2)

f30 = Frame(root)
l3 = Label(f30, image = pic19)
l3.grid(row = 3,column=2)
l4 = Label(f30, text = "Thomas Jefferson, left, and John Adams, right, became bitter rivals in the election of 1800.", font=('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f30, text="This looks interesting, tell me more", command=notes_26)
btn2.grid(row=5, column=2)

f31 = Frame(root)
l3 = Label(f31, text= "Details on the election: ", font = ('Arial', 13))
l3.grid(row = 3,column=2)
l4 = Label(f31, text = "The election of 1800 pitted Democratic-Republican Thomas Jefferson against Federalist John Adams.												The election was a referendum on two different visions of America. The Federalists envisioned a strong central government and a thriving manufacturing sector, while the Democratic-Republicans yearned for an agrarian republic centered on the values of the yeoman farmer. 							The election of 1800 was one of the most bitter, contentious, and fiercely partisan presidential elections in US history.																						The major political questions and conflicts during the 1790s concerned foreign policy, economic policy, and the balance of power between states and the federal government.																							During Washington's presidency, factions began to emerge that would soon form the first two political parties in the United States: the Democratic-Republicans and the Federalists.																				Washington’s decision to stay neutral during the French Revolution set a precedent for the United States government to practice isolationism as its main foreign policy strategy for over a hundred years.", font=('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f31, text="Cool, what's next", command=notes_27)
btn2.grid(row=5, column=2)

f32 = Frame(root)
l3 = Label(f32, image = pic20)
l3.grid(row = 3,column=2)
l4 = Label(f32, text = "This over here is the Louisiana Purchase ", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f32, text="This looks interesting, tell me more", command=notes_28)
btn2.grid(row=5, column=2)

f33 = Frame(root)
l4 = Label(f33, text = "The Louisiana Purchase doubled the size of the United States, reshaping the environmental and economic makeup of the country.																	Jefferson confronted questions of presidential authority in deciding whether or not to acquire the territory, since the US Constitution does not explicitly give the president the power to purchase territory.																				Jefferson enlisted Meriwether Lewis and William Clark to explore the new uncharted territory and secured Congressional funding for their expedition.", font=('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f33, text="Cool, what's next", command=notes_29)
btn2.grid(row=5, column=2)

f34 = Frame(root)
l3 = Label(f34, image = pic21)
l3.grid(row = 3,column=2)
l4 = Label(f34, text = "This here is the trail of tears that Andrew Jackson used to execute native Americans ", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f34, text="Umm, ok", command=notes_30)
btn2.grid(row=5, column=2)

f35 = Frame(root)
l3 = Label(f35, text = "Facts about this", font = ('Arial', 13))
l3.grid(row = 3,column=2)
l4 = Label(f35, text = "US President Andrew Jackson oversaw the policy of 'Indian removal,' which was formalized when he signed the Indian Removal Act in May 1830.																The Indian Removal Act authorized a series of migrations that became known as the Trail of Tears.															This was devastating to Native Americans, their culture, and their way of life. ", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f35, text="This looks interesting, tell me more", command=notes_31)
btn2.grid(row=5, column=2)

f36 = Frame(root)
l3 = Label(f36, image = pic22)
l3.grid(row = 3,column=2)
l4 = Label(f36, text = "Henry Doyle, Emigrants leaving Ireland, 1868, engraving. ", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f36, text="What's next", command=notes_32)
btn2.grid(row=5, column=2)

f37 = Frame(root)
l3 = Label(f37, text = "German and Irish immigration", font = ('Arial', 13))
l3.grid(row = 3,column=2)
l4 = Label(f37, text = "From the 1820s to the 1840s, Germans and Irish were the two largest groups of immigrants to the United States.																		The Germans and Irish were frequently subjected to anti-foreign prejudice and discrimination.																			Ultimately, the Germans and Irish assimilated into US culture and society and became two of the most successful immigrant groups in the country. ", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f37, text="This looks interesting, tell me more", command=notes_33)
btn2.grid(row=5, column=2)

f38 = Frame(root)
l3 = Label(f38, image = pic23)
l3.grid(row = 3,column=2)
l4 = Label(f38, text = "Left, Henry David Thoreau; right, Ralph Waldo Emerson.", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f38, text="Who are they?", command=notes_34)
btn2.grid(row=5, column=2)


f39 = Frame(root)
l3 = Label(f39, text = "They are: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f39, text = "The philosophy of transcendentalism arose in the 1830s in the eastern United States as a reaction to intellectualism. Its adherents yearned for intense spiritual experiences and sought to transcend the purely material world of reason and rationality.																		Ralph Waldo Emerson and Henry David Thoreau were two of the most famous and influential transcendentalists. 																								Some influential transcendentalists, such as Margaret Fuller, were early pioneers of feminism.", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f39, text="What's next", command=notes_35)
btn2.grid(row=5, column=2)

f40 = Frame(root)
l3 = Label(f40, image = pic24)
l3.grid(row = 3,column=2)
l4 = Label(f40, text = "Sarah and Angelina Grimké. ", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f40, text="Tell me about them", command= notes_36)
btn2.grid(row=5, column=2)

f41 = Frame(root)
l3 = Label(f41, text = "Facts about the Seneca Falls Convention" , font = ("Arial", 13))
l3.grid(row = 3,column=2)
l4 = Label(f41, text = "The women’s rights movement of the mid-1800s gained traction through abolitionist sentiment and religious fervor surrounding the Second Great Awakening.																	The Declaration of Rights and Sentiments, published at the Seneca Falls Convention in 1848, used constitutional language to underline the inconsistencies between national commitments to human equality and the treatment of women.																																			Women leveraged their specialty in all things involving the private sphere—the home—to organize and empower white women.. ", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f41, text="Next topic", command=notes_37)
btn2.grid(row=5, column=2)

f42= Frame(root)
l3 = Label(f42, image = pic25)
l3.grid(row = 3,column=2)
l4 = Label(f42, text = "Model of a nineteenth-century cotton gin. ", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f42, text="What's next", command=notes_38)
btn2.grid(row=5, column=2)

f43 = Frame(root)
l3 = Label(f43, text = "About this era: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f43, text = "During the first half of the nineteenth century, demand for cotton led to the expansion of plantation slavery.																			By 1850, enslaved people were growing cotton from South Carolina to Texas.. ", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f43, text="What's next", command=notes_39)
btn2.grid(row=5, column=2)

f44 = Frame(root)
l3 = Label(f44, image = pic26)
l3.grid(row = 3,column=2)
l4 = Label(f44, text = "John Gast, American Progress, 1872. The artist depicts Columbia, an allegorical figure of America, bring elements of 'civilization' west. As railroads, settlers, and telegraph wires come west, American Indians and bison scatter before them ", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f44, text="Unit 5!!", command=notes_40)
btn2.grid(row=5, column=2)

f45 = Frame(root)
l3 = Label(f45, text = "About this era: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f45, text = "Manifest Destiny was the idea that white Americans were divinely ordained to settle the entire continent of North America.																The ideology of Manifest Destiny inspired a variety of measures designed to remove or destroy the native population.																				US President James K. Polk (1845-1849) is the leader most associated with Manifest Destiny.														Manifest Destiny inflamed sectional tensions over slavery, which ultimately led to the Civil War. ", font = ('Arial', 13),wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f45, text="What's next", command=notes_41)
btn2.grid(row=5, column=2)

f46 = Frame(root)
l3 = Label(f46, image = pic27)
l3.grid(row = 3,column=2)
l4 = Label(f46, text = "The Mexican Cession. ", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f46, text="Tell me about this", command=notes_42)
btn2.grid(row=5, column=2)

f47 = Frame(root)
l3 = Label(f47, text = "About this era: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f47, text = "The Compromise of 1850 acted as a temporary truce on the issue of slavery, primarily addressing the status of newly acquired territory after the Mexican-American War.																					Under the Compromise, California was admitted to the Union as a free state; the slave trade was outlawed in Washington, D.C., a strict new Fugitive Slave Act compelled citizens of free states to assist in capturing enslaved people; and the new territories of Utah and New Mexico would permit white residents to decide whether to allow slavery.																														Ultimately, the Compromise did not resolve the issue of slavery’s expansion; instead, the fiery rhetoric surrounding the Compromise further polarized the North and the South.. ", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f47, text="What's next", command=notes_43)
btn2.grid(row=5, column=2)

f48 = Frame(root)
l3 = Label(f48, image = pic28)
l3.grid(row = 3,column=2)
l4 = Label(f48, text = "John Brown. ", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f48, text="Who is he?", command=notes_44)
btn2.grid(row=5, column=2)

f49 = Frame(root)
l3 = Label(f49, text = "About this: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f49, text = "After the Kansas-Nebraska Act reopened the possibility of slavery extending into new territories, tensions between pro- and anti-slavery advocates erupted into violence.																			Radical abolitionists, like John Brown, attacked and murdered white southerners in protest. A pro-slavery US Senator, Preston Brooks, viciously beat abolitionist Senator Charles Sumner on the floor of the Senate.															Bleeding Kansas foreshadowed the violence that would ensue over the future of slavery during the Civil War. ", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f49, text="What's next", command=notes_45)
btn2.grid(row=5, column=2)

f50 = Frame(root)
l3 = Label(f50,  image = pic29)
l3.grid(row = 3,column=2)
l4 = Label(f50, text = "The United States during the Civil War ", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f50, text="Next page", command=notes_46)
btn2.grid(row=5, column=2)

f51 = Frame(root)
l3 = Label(f51, text = "About this: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f51, text = "When Lincoln became president, he had had no intention of abolishing slavery. Though he personally despised slavery, and had won the presidency on an anti-slavery platform, he would gladly have given up any chance of ending slavery in the South if it meant that the Confederate states would rejoin the United States.					.", font = ("Arial", 13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f51, text="What's next", command=notes_47)
btn2.grid(row=5, column=2)

f52 = Frame(root)
l3 = Label(f52,  image = pic30)
l3.grid(row = 3,column=2)
l4 = Label(f52, text = "Rutherford B. Hayes won the contested election of 1876 as a result of the Compromise of 1877 ", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f52, text="Next page", command=notes_48)
btn2.grid(row=5, column=2)

f53 = Frame(root)
l3 = Label(f53, text = "About this: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f53, text = "The Compromise of 1877 resolved the disputed 1876 presidential election between Democratic candidate Samuel Tilden and Republican candidate Rutherford B. Hayes.																				Democrats agreed that Rutherford B. Hayes would become president in exchange for the withdrawal of federal troops from the South and the granting of home rule in the South.															President Hayes’ withdrawal of federal troops from Louisiana and South Carolina marked a major turning point in American political history, effectively ending the Reconstruction Era and issuing in the system of Jim Crow.", font = ("Arial", 13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f53, text="What's next", command=notes_49)
btn2.grid(row=5, column=2)

f54 = Frame(root)
l3 = Label(f54,  image = pic31)
l3.grid(row = 3,column=2)
l4 = Label(f54, text = "Illustration of a Freedmen's Bureau school, Frank Leslie's Illustrated Newspaper ", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f54, text="What does it signify?", command=notes_50)
btn2.grid(row=5, column=2)

f55 = Frame(root)
l3 = Label(f55, text = "About this: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f55, text = "The Thirteenth Amendment (1865) ended slavery, and slavery’s end meant newfound freedom for African Americans.													During the period of Reconstruction, some 2000 African Americans held government jobs.																							The black family, the black church, and education were central elements in the lives of post-emancipation African Americans.							Many African Americans lived in desperate rural poverty across the South in the decades following the Civil War.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f55, text="Unit 6!", command=notes_51)
btn2.grid(row=5, column=2)

f56 = Frame(root)
l3 = Label(f56,  image = pic32)
l3.grid(row = 3,column=2)
l4 = Label(f56, text = "Map of the areas in Northern California to which gold prospectors flocked", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f56, text="The Notes please", command=notes_52)
btn2.grid(row=5, column=2)

f57 = Frame(root)
l3 = Label(f57, text = "Learn these concepts", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f57, text = "The 1848 discovery of gold in California set off a frenzied Gold Rush to the state the next year as hopeful prospectors, called “forty-niners,” poured into the state.																	This massive migration to California transformed the state’s landscape and population.																																The Gold Rush was characterized by violent clashes among settlers, miners, and Native Americans over access to the land and its natural resources.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f57, text="Next topic", command=notes_53)
btn2.grid(row=5, column=2)

f58 = Frame(root)
l3 = Label(f58,  image = pic33)
l3.grid(row = 3,column=2)
l4 = Label(f58, text = "Drawing depicting Chinese laborers building a railroad.", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f58, text="Tell me more", command=notes_54)
btn2.grid(row=5, column=2)

f59 = Frame(root)
l3 = Label(f59, text = "Read this: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f59, text = "In the nineteenth century, Mexican American, Chinese, and white populations of the United States collided as white people moved farther west in search of land and riches.																																		Neither Chinese immigrants nor Mexican Americans could withstand the assault on their rights by the tide of white settlers. Ultimately, both ethnic groups retreated into urban enclaves, where their language and traditions could survive.																																				Las Gorras Blancas, the White Caps, were a rebel group of Mexican Americans who fought back against the appropriation of their land by white settlers; in 1889 and 1890, they burned farms, homes, and crops.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f59, text="Next page", command=notes_55)
btn2.grid(row=5, column=2)

f60 = Frame(root)
l3 = Label(f60,  image = pic34)
l3.grid(row = 3,column=2)
l4 = Label(f60, text = "Sharecroppers in Georgia, c. 1910. Both white and black farm laborers worked in the sharecropping", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f60, text="What about this", command=notes_56)
btn2.grid(row=5, column=2)

f61 = Frame(root)
l3 = Label(f61, text = "Read this: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f61, text = "Proponents of the New South envisioned a post-Reconstruction southern economy modeled on the North’s embrace of the Industrial Revolution.																																					Henry W. Grady, a newspaper editor in Atlanta, Georgia, coined the phrase the 'New South' in 1874. He urged the South to abandon its longstanding agrarian economy for a modern economy grounded in factories, mines, and mills.																																														Although textile mills and tobacco factories emerged in the South during this time, the plans for a New South largely failed. By 1900, per-capita income in the South was forty percent less than the national average, and rural poverty persisted across much of the South well into the twentieth century.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f61, text=" Next", command=notes_57)
btn2.grid(row=5, column=2)

f62 = Frame(root)
l3 = Label(f62,  image = pic35)
l3.grid(row = 3,column=2)
l4 = Label(f62, text = "Print showing the leaders of the Knights of Labor. Terence Powderly is pictured at center.", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f62, text="Who is he?", command=notes_58)
btn2.grid(row=5, column=2)

f63 = Frame(root)
l3 = Label(f63, text = "About him and what he did: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f63, text = "Labor unions arose in the nineteenth century as increasing numbers of Americans took jobs in factories, mines, and mills in the growing industrial economy.																												The Knights of Labor, founded in 1869, was the first major labor organization in the United States. The Knights organized unskilled and skilled workers, campaigned for an eight hour workday, and aspired to form a cooperative society in which laborers owned the industries in which they worked.																																										The Knights’ membership collapsed following the 1886 Haymarket Square riot in Chicago. By 1886 the American Federation of Labor (AFL), an alliance of skilled workers’ trade unions, was growing.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f63, text="Next!", command=notes_59)
btn2.grid(row=5, column=2)

f64 = Frame(root)
l3 = Label(f64,  image = pic36)
l3.grid(row = 3,column=2)
l4 = Label(f64, text = "Chicago's Home Insurance Building is considered the world's first skyscraper. At 10 stories tall, it seems small by modern standards, but it was the tallest modern building in the world from 1884-1889", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f64, text="What about this?", command=notes_60)
btn2.grid(row=5, column=2)

f65 = Frame(root)
l3 = Label(f65, text = "Why that picture was relevant? ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f65, text = "Americans increasingly moved into cities over the course of the late nineteenth and early twentieth centuries, a movement motivated in large measure by industrialization.																																												Eleven million people migrated from rural to urban areas between 1870 and 1920, and a majority of the twenty-five million immigrants who came to the United States in these same years moved into the nation’s cities.																																															By 1920, more Americans lived in cities than in rural areas for the first time in US history.								", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f65, text="After this", command=notes_61)
btn2.grid(row=5, column=2)

f66 = Frame(root)
l3 = Label(f66,  image = pic37)
l3.grid(row = 3,column=2)
l4 = Label(f66, text = "1872 presidential campaign poster for Horace Greeley, who ran on a Liberal Republican platform", font = ('Arial', 13))
l4.grid(row=4, column =2)	
btn2=Button(f66, text="Cool", command=notes_62)
btn2.grid(row=5, column=2)

f67 = Frame(root)
l3 = Label(f67, text = "About Laissez-Faire", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f67, text = "During the Gilded Age, proponents of laissez-faire policies opposed government intervention in society or the market.																												Laissez-faire ideology influenced government policies toward labor relations and Reconstruction.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f67, text="Next Please", command=notes_63)
btn2.grid(row=5, column=2)

f68 = Frame(root)
l3 = Label(f68,  image = pic38)
l3.grid(row = 3,column=2)
l4 = Label(f68, text = "This here is the notorious Boss Tweed who used to make decisions for voters", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f68, text="More about this", command=notes_64)
btn2.grid(row=5, column=2)

f69 = Frame(root)
l3 = Label(f69, text = "What you should know: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f69, text = "Politics in the Gilded Age were characterized by scandal and corruption, but voter turnout reached an all-time high.																The Republican Party supported business and industry with a protective tariff and hard money policies.																										The Democratic Party opposed the tariff and eventually adopted the free silver platform.																															The People's (Populist) Party emerged in the 1890s to champion the interests of farmers. The party endorsed the coinage of silver to improve the financial situation of debtors.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f69, text="To Unit 7", command=notes_65)
btn2.grid(row=5, column=2)

f70 = Frame(root)
l3 = Label(f70,  image = pic39)
l3.grid(row = 3,column=2)
l4 = Label(f70, text = "Illustration on the cover of Puck magazine, 1901, showing Columbia (the allegorical representation of the United States) trying on a new hat: world power", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f70, text="Next", command=notes_66)
btn2.grid(row=5, column=2)

f71 = Frame(root)
l3 = Label(f71, text = "About the U.S. during this era", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f71, text = "In the late nineteenth century, the United States abandoned its century-long commitment to isolationism and became an imperial power.																	After the Spanish-American War, the United States exercised significant control over Cuba, annexed Hawaii, and claimed Guam, Puerto Rico, and the Philippines as territories.																																				Both a desire for new markets for its industrial products and a belief in the racial and cultural superiority of Americans motivated the United States' imperial mission.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f71, text="Next topic", command=notes_67)
btn2.grid(row=5, column=2)

f72 = Frame(root)
l3 = Label(f72,  image = pic40)
l3.grid(row = 3,column=2)
l4 = Label(f72, text = "Painting depicting the sinking of the USS Maine", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f72, text="Tell me more", command=notes_68)
btn2.grid(row=5, column=2)

f73 = Frame(root)
l3 = Label(f73, text = "About the Spanish-American Wars", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f73, text = "The Cuban movement for independence from Spain in 1895 garnered considerable American support. When the USS Maine sank, the United States believed the tragedy was the result of Spanish sabotage and declared war on Spain.																																									The Spanish-American War lasted only six weeks and resulted in a decisive victory for the United States. Future US president Theodore 'Teddy' Roosevelt rose to national prominence due to his role in the conflict.																																						Although the United States promised it would not annex Cuba after victory, it did require Cuba to permit significant American intervention in Cuban affairs.																															As a result of the war, the United States acquired Puerto Rico, Guam, and the Philippines as territories", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f73, text="interesting", command=notes_69)
btn2.grid(row=5, column=2)

f74 = Frame(root)
l3 = Label(f74,  image = pic41)
l3.grid(row = 3,column=2)
l4 = Label(f74, text = "In response to Upton Sinclair's novel The Jungle, Congress passed the Meat Inspection Act of 1906", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f74, text="Eww, next please", command=notes_70)
btn2.grid(row=5, column=2)

f75 = Frame(root)
l3 = Label(f75, text = "About Muckrakers", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f75, text = "Muckrakers were journalists and novelists of the Progressive Era who sought to expose corruption in big business and government.																							The work of muckrakers influenced the passage of key legislation that strengthened protections for workers and consumers.																																						Some of the most famous muckrakers were women, including Ida Tarbell and Ida B. Wells", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f75, text="Wow next please", command=notes_71)
btn2.grid(row=5, column=2)

f76 = Frame(root)
l3 = Label(f76,  image = pic42)
l3.grid(row = 3,column=2)
l4 = Label(f76, text = "Woodrow Wilson", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f76, text="Tell me more", command=notes_72)
btn2.grid(row=5, column=2)

f77 = Frame(root)
l3 = Label(f77, text = "About Woodrow Wilson", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f77, text = "Woodrow Wilson was the 28th president of the United States. He served two terms in office, from 1913 to 1921.																										Wilson was a Progressive Democrat who believed in the power of the federal government to expose corruption, regulate the economy, eliminate unethical business practices, and improve the general condition of society.																							During Wilson’s years in office, the US federal government was segregated and the Ku Klux Klan experienced a major revival.																											Wilson’s second term in office was dominated by the First World War. Though Wilson campaigned on the slogan “He kept us out of war,” escalating German aggression ultimately made it impossible for the United States to stay out of the conflict.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f77, text="I need to know more", command=notes_73)
btn2.grid(row=5, column=2)

f78 = Frame(root)
l3 = Label(f78,  image = pic43)
l3.grid(row = 3,column=2)
l4 = Label(f78, text = "World War I was truly a world-wide war. Here, countries that were allied with the Triple Entente, known as the Allied Powers, are highlighted in green. Countries that were allied with the Central Powers are highlighted in orange", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f78, text="Oh this is getting interesting", command=notes_74)
btn2.grid(row=5, column=2)

f79 = Frame(root)
l3 = Label(f79, text = "About WW1", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f79, text = "World War I was the deadliest conflict until that point in human history, claiming tens of millions of casualties on all sides.																						Under President Woodrow Wilson, the United States remained neutral until 1917 and then entered the war on the side of the Allied powers (the United Kingdom, France, and Russia).																												The experience of World War I had a major impact on US domestic politics, culture, and society. Women achieved the right to vote, while other groups of American citizens were subject to systematic repression", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f79, text=" Post WW1", command=notes_75)
btn2.grid(row=5, column=2)

f80 = Frame(root)
l3 = Label(f80,  image = pic44)
l3.grid(row = 3,column=2)
l4 = Label(f80, text = "This advertisement for Ford’s Model T ran in the New Orleans Times Picayune in 1911. Note that the prices had not yet dropped far from their initial high of $850", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f80, text="Oh boy, an economic bubble!", command=notes_76)
btn2.grid(row=5, column=2)

f81 = Frame(root)
l3 = Label(f81, text = "About the Roaring 20s", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f81, text = "For many middle-class Americans, the 1920s was a decade of unprecedented prosperity. Rising earnings generated more disposable income for the purchase of consumer goods																												Henry Ford’s advances in assembly-line efficiency created a truly affordable automobile, making car ownership a possibility for many Americans.																														Advertising became as big an industry as the manufactured goods that advertisers represented, and many families relied on new forms of credit to increase their consumption levels as they strived for a new American standard of living.							", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f81, text="Does the bubble burst?", command=notes_77)
btn2.grid(row=5, column=2)

f82 = Frame(root)
l3 = Label(f82,  image = pic45)
l3.grid(row = 3,column=2)
l4 = Label(f82, text = "The Great Depression has begun", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f82, text="Damn, what's next?", command=notes_78)
btn2.grid(row=5, column=2)

f83 = Frame(root)
l3 = Label(f83, text = "Life during the Great Depression", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f83, text = "The Great Depression was the worst economic downturn in US history. It began in 1929 and did not abate until the end of the 1930s.																																												The stock market crash of October 1929 signaled the beginning of the Great Depression. By 1933, unemployment was at 25 percent and more than 5,000 banks had gone out of business.																			Although President Herbert Hoover attempted to spark growth in the economy through measures like the Reconstruction Finance Corporation, these measures did little to solve the crisis.		Franklin Roosevelt was elected president in November 1932. Inaugurated as president in March 1933, Roosevelt’s New Deal offered a new approach to the Great Depression.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f83, text="How do we get out of this?", command=notes_79)
btn2.grid(row=5, column=2)

f84 = Frame(root)
l3 = Label(f84,  image = pic46)
l3.grid(row = 3,column=2)
l4 = Label(f84, text = "Political cartoon satirizing the 'alphabet agencies' of the New Deal. Even contemporaries had trouble remembering all the acronyms", font = ('Arial', 13),wraplength= 400)
l4.grid(row=4, column =2)
btn2=Button(f84, text="I like this", command=notes_80)
btn2.grid(row=5, column=2)

f85 = Frame(root)
l3 = Label(f85, text = "FDR and the New Deal", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f85, text = "The New Deal was a set of domestic policies enacted under President Franklin D. Roosevelt that dramatically expanded the federal government’s role in the economy in response to the Great Depression.																															Historians commonly speak of a First New Deal (1933-1934), with the “alphabet soup” of relief, recovery, and reform agencies it created, and a Second New Deal (1935-1938) that offered further legislative reforms and created the groundwork for today’s modern social welfare system.																															It was the massive military expenditures of World War II, not the New Deal, that eventually pulled the United States out of the Great Depression", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f85, text="economic growth time!!", command=notes_81)
btn2.grid(row=5, column=2)

f86 = Frame(root)
l3 = Label(f86,  image = pic47)
l3.grid(row = 3,column=2)
l4 = Label(f86, text = "British soldiers receive a shipment of American weapons provided by the Lend-Lease Act", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f86, text="Oh boy, WW2", command=notes_82)
btn2.grid(row=5, column=2)

f87 = Frame(root)
l3 = Label(f87, text = "About WW2 and America", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f87, text = "Democrat Franklin Delano Roosevelt led the nation through the Second World War.																																				Roosevelt built a powerful wartime coalition with Britain and the Soviet Union, and led the nation to victory against Nazi Germany.																																																							His wartime efforts prepared the path for his successor, Harry Truman, to win the war against Japan four months after his death.																												He was elected to the presidency four times, serving from March 1933 until his death in office in April 1945.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f87, text="What's after this?", command=notes_83)
btn2.grid(row=5, column=2)

f88 = Frame(root)
l3 = Label(f88,  image = pic48)
l3.grid(row = 3,column=2)
l4 = Label(f88, text = "The United Nations was formed", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f88, text="Yay! World Peace", command=notes_84)
btn2.grid(row=5, column=2)

f89 = Frame(root)
l3 = Label(f89, text = "What happened post WW2", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f89, text = "The United Nations (UN) was created at the end of World War II as an international peacekeeping organization and a forum for resolving conflicts between nations.																																			The UN replaced the ineffective League of Nations, which had failed to prevent the outbreak of the Second World War.																																										The UN was established on October 24, 1945, with headquarters in Manhattan, New York City, and reflected the rise of the United States to global leadership in the postwar period.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f89, text="Unit 8!", command=notes_85)
btn2.grid(row=5, column=2)

f90 = Frame(root)
l3 = Label(f90,  image = pic49)
l3.grid(row = 3,column=2)
l4 = Label(f90, text = "Map of partitioned Germany showing the nations in control of each region: England in the northwest, France in the southwest, the United States in the southeast, and the Soviet Union in the northeast. Note that the city of Berlin, which was itself divided among the four powers, fell within the Soviet region", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f90, text="What else", command=notes_86)
btn2.grid(row=5, column=2)

f91 = Frame(root)
l3 = Label(f91, text = "What was also happening at this period", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f91, text = "Tensions between the United States and the Soviet Union came to a head in 1948, when the Soviet Union blockaded Berlin and the United States led a year-long airlift to supply citizens stranded in the western zone of the city.																																		Realizing that conflict with the Soviet Union might escalate into war, the United States joined the North Atlantic Treaty Organization (NATO) defensive alliance and ramped up security measures at home with the National Security Act.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f91, text="Afterwards", command=notes_87)
btn2.grid(row=5, column=2)

f92 = Frame(root)
l3 = Label(f92,  image = pic50)
l3.grid(row = 3,column=2)
l4 = Label(f92, text = "Rock musician Elvis Presley enthralled teens and scandalized adults with his suggestive lyrics and dance moves", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f92, text="Yay the Zenith 50s", command=notes_88)
btn2.grid(row=5, column=2)

f93 = Frame(root)
l3 = Label(f93, text = "About this age", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f93, text = "In the 1950s and 1960s, young Americans had more disposable income and enjoyed greater material comfort than their forebears, which allowed them to devote more time and money to leisure activities and the consumption of popular culture.																																Rock and roll, a new style of music which drew inspiration from African American blues music, embraced themes popular among teenagers, such as young love and rebellion against authority.																																											In the 1950s, the relatively new technology of television began to compete with motion pictures as a major form of popular entertainment.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f93, text="Cool, what else", command=notes_89)
btn2.grid(row=5, column=2)

f94 = Frame(root)
l3 = Label(f94,  image = pic51)
l3.grid(row = 3,column=2)
l4 = Label(f94, text = "Astronaut John Glenn became the first American to enter Earth's orbit in 1962", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f94, text="Wow, I want to know more about this unit!", command=notes_90)
btn2.grid(row=5, column=2)

f95 = Frame(root)
l3 = Label(f95, text = "About the Space Race and more", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f95, text = "The “space race” was a Cold War competition between the United States and the Soviet Union to develop aerospace capabilities, including artificial satellites, unmanned space probes, and human spaceflight.																																			The National Aeronautics and Space Administration (NASA) was created in 1958 as the federal agency with primary responsibility for the development of civilian aerospace research. 																																										Early Soviet successes in the space race had a major impact on US society and culture, altering strategic defense doctrines and leading to new educational initiatives.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f95, text="Oh boy, more escalation", command=notes_91)
btn2.grid(row=5, column=2)

f96 = Frame(root)
l3 = Label(f96,  image = pic52)
l3.grid(row = 3,column=2)
l4 = Label(f96, text = "Map of Vietnam. The 17th Parallel indicates the boundary separating North and South Vietnam following the peace negotiations in Geneva in 1954", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f96, text="Next page", command=notes_92)
btn2.grid(row=5, column=2)

f97 = Frame(root)
l3 = Label(f97, text = "About Vietnam", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f97, text = "The Vietnam War was a prolonged military conflict that started as an anticolonial war against the French and evolved into a Cold War confrontation between international communism and free-market democracy.																	The Democratic Republic of Vietnam (DRV) in the north was supported by the Soviet Union, China, and other communist countries, while the United States and its anticommunist allies backed the Republic of Vietnam (ROV) in the south. 																										President Lyndon Johnson dramatically escalated US involvement in the conflict, authorizing a series of intense bombing campaigns and committing hundreds of thousands of US ground troops to the fight.																																	After the United States withdrew from the conflict, North Vietnam invaded the South and united the country under a communist government.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f97, text="Woah, we're losing?", command=notes_93)
btn2.grid(row=5, column=2)

f98 = Frame(root)
l3 = Label(f98,  image = pic53)
l3.grid(row = 3,column=2)
l4 = Label(f98, text = "Lyndon Johnson's swearing-in ceremony on Air Force One, just hours after Kennedy's assassination. Former First Lady Jacqueline Kennedy stands next to Johnson", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f98, text="Next", command=notes_94)
btn2.grid(row=5, column=2)

f99 = Frame(root)
l3 = Label(f99, text = "Lyndon Johnson as president", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f99, text = "Lyndon Johnson became president of the United States after the assassination of John F. Kennedy in November 1963. He served as president from 1963-1969.																																			The Great Society, a package of programs and legislation aimed at eradicating poverty and improving health care and education, was President Johnson’s chief domestic policy program and one of his permanent legacies.																																				President Johnson vastly expanded the US military role in Vietnam.																																									Johnson chose not to run for re-election in 1968, largely due to the Vietnam debacle and the disarray of the Democratic Party. He was succeeded in office by Richard Nixon", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f99, text=" What's next", command=notes_95)
btn2.grid(row=5, column=2)

f100 = Frame(root)
l3 = Label(f100,  image = pic54)
l3.grid(row = 3,column=2)
l4 = Label(f100, text = "Civil rights activists marching from Selma to Montgomery, Alabama, in March 1965", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f100, text="Next", command=notes_96)
btn2.grid(row=5, column=2)

f101 = Frame(root)
l3 = Label(f101, text = "What you should know: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f101, text = "The Civil Rights Act of 1964 was the most comprehensive civil rights legislation ever enacted by Congress. It contained extensive measures to dismantle Jim Crow segregation and combat racial discrimination.																The Voting Rights Act of 1965 removed barriers to black enfranchisement in the South, banning poll taxes, literacy tests, and other measures that effectively prevented African Americans from voting.																																Segregationists attempted to prevent the implementation of federal civil rights legislation at the local level.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f101, text="What's after this", command=notes_97)
btn2.grid(row=5, column=2)

f102 = Frame(root)
l3 = Label(f102,  image = pic55)
l3.grid(row = 3,column=2)
l4 = Label(f102, text = "Campaign rally for Richard Nixon in 1968", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f102, text="Next", command=notes_98)
btn2.grid(row=5, column=2)

f103 = Frame(root)
l3 = Label(f103, text = "Points to Remember", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f103, text = "Richard Nixon was elected president in 1968, a tumultuous year that witnessed the assassinations of Martin Luther King, Jr. and Robert F. Kennedy, as well as the splintering of the Democratic Party.																																													Nixon’s presidential campaign sought to appeal to what it deemed the “silent majority,” those middle-class white Americans who defended the status quo against radical social change.																																																		Nixon’s campaign successfully employed the “Southern strategy,” an attempt to appeal to Southern racists resentful of civil rights activism and federal antipoverty programs.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f103, text="What downfall, what else happened?", command=notes_99)
btn2.grid(row=5, column=2)

f104 = Frame(root)
l3 = Label(f104,  image = pic56)
l3.grid(row = 3,column=2)
l4 = Label(f104, text = "Line at a gas station in 1979", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f104, text="Next Page", command=notes_100)
btn2.grid(row=5, column=2)

f105 = Frame(root)
l3 = Label(f105, text = "An overview", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f105, text = "In the early 1970s, the post-World War II economic boom began to wane, due to increased international competition, the expense of the Vietnam War, and the decline of manufacturing jobs. 																																		Unemployment rates rose, while a combination of price increases and wage stagnation led to a period of economic doldrums known as stagflation. President Nixon tried to alleviate these problems by devaluing the dollar and declaring wage- and price-freezes. 																																							The crisis was compounded when oil-rich nations in the Middle East declared an embargo against the United States in retaliation for its support of Israel. The oil embargo had a lasting effect on energy prices.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f105, text="Next Topic", command=notes_101)
btn2.grid(row=5, column=2)

f106 = Frame(root)
l3 = Label(f106,  image = pic57)
l3.grid(row = 3,column=2)
l4 = Label(f106, text = "Official White House portrait of Jimmy Carter", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f106, text="Is he any good? ", command=notes_102)
btn2.grid(row=5, column=2)

f107 = Frame(root)
l3 = Label(f107, text = "Points to Remember", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f107, text = "Democrat Jimmy Carter served as president of the United States from 1977 to 1981.																																	Carter was unable to solve most of the problems plaguing the country during his administration, including an ailing economy and a continuing energy crisis.																																	Although Carter brokered the historic Camp David Accords between Israel and Egypt, relations with the Middle East broke down after the Iranian Revolution in 1979. Iranian extremists seized the American embassy in Tehran and held 52 American hostages captive there for over a year", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f107, text="Unit 9!!!!!!", command=notes_103)
btn2.grid(row=5, column=2)

f108 = Frame(root)
l3 = Label(f108,  image = pic58)
l3.grid(row = 3,column=2)
l4 = Label(f108, text = "Official portrait of President Reagan", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f108, text="Next ", command=notes_104)
btn2.grid(row=5, column=2)

f109 = Frame(root)
l3 = Label(f109, text = "Important Information: ", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f109, text = "Ronald Reagan, a conservative Republican, won the 1980 presidential election in a landslide. He won reelection in 1984 by one of the largest margins in US history.																					Reagan’s campaign brought together a “New Right” coalition of economic conservatives, members of the Christian Right, working-class whites, and supporters of a more aggressive Cold War foreign policy. 																																	President Reagan initially engineered large tax cuts, but as deficits grew proposed select tax increases. Over the course of his presidency, inflation and unemployment fell, while the national debt nearly tripled.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f109, text="Is this why America sucks?", command=notes_105)
btn2.grid(row=5, column=2)

f110 = Frame(root)
l3 = Label(f110,  image = pic59)
l3.grid(row = 3,column=2)
l4 = Label(f110, text = "Map of the Persian Gulf region", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f110, text="Tell me more", command=notes_106)
btn2.grid(row=5, column=2)

f111 = Frame(root)
l3 = Label(f111, text = "An overview of the war", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f111, text = "In August 1990, Iraq invaded the country of Kuwait to its southeast in a bid to gain more control over the lucrative oil supply of the Middle East.																											In response, the United States and the UN Security Council demanded that Iraqi dictator Saddam Hussein withdraw Iraqi troops from Kuwait, but Hussein refused.																																										Over the course of six weeks in January and February 1991, a United States-led coalition of 34 nations began an intensive bombing campaign against strategic Iraqi locations, culminating with a four-day ground campaign against Iraqi forces known as Operation Desert Storm.																																							At the end of February, Hussein signed a cease-fire agreement and released Kuwait. After the war, Iraq was required to submit to inspections to ensure it possessed no chemical or other weapons of mass destruction.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f111, text="More wars wow", command=notes_107)
btn2.grid(row=5, column=2)

f112 = Frame(root)
l3 = Label(f112,  image = pic60)
l3.grid(row = 3,column=2)
l4 = Label(f112, text = "A McDonald's restaurant in St. Petersburg. After the fall of the Soviet Union, the former communist bloc nations began to integrate into the global economy", font = ('Arial', 13), wraplength = 400)
l4.grid(row=4, column =2)
btn2=Button(f112, text="Yay! Another American victory", command=notes_108)
btn2.grid(row=5, column=2)

f113 = Frame(root)
l3 = Label(f113, text = "Points on Globalization", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f113, text = "Globalization refers to the process by which technological, economic, political, and cultural exchanges make the world a more interconnected and interdependent place.																														Although the phenomenon of globalization is not new, political, economic, and technological developments in the 1990s accelerated the processes of globalization and contributed to the emergence of a public debate about its advantages and disadvantages.																					The effects of globalization have been uneven, with some people, industries, and countries benefiting more than others", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f113, text="Next Page", command=notes_109)
btn2.grid(row=5, column=2)

f114 = Frame(root)
l3 = Label(f114,  image = pic61)
l3.grid(row = 3,column=2)
l4 = Label(f114, text = "Official White House portrait of Bill Clinton", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f114, text="What about Bill", command=notes_110)
btn2.grid(row=5, column=2)

f115 = Frame(root)
l3 = Label(f115, text = "", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f115, text = "Bill Clinton was the 42nd president of the United States. He was elected in 1992 and reelected in 1996, becoming the first Democratic president since Franklin D. Roosevelt to serve two terms in office.																															Clinton came to the White House with an ambitious domestic policy agenda centered on economic growth and immediately took steps to reduce the federal budget deficit.																				Clinton’s second term was marred by scandal, as he was impeached for lying to Congress and the American people about an extramarital affair with White House intern Monica Lewinsky.																							Despite the Lewinsky affair, Clinton left the White House with the highest approval rating of any US president in the post-World War II era.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f115, text="Ok, next", command=notes_111)
btn2.grid(row=5, column=2)

f116 = Frame(root)
l3 = Label(f116,  image = pic62)
l3.grid(row = 3,column=2)
l4 = Label(f116, text = "Official White House photo portrait of George W. Bush.", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f116, text="What about Bush?", command=notes_112)
btn2.grid(row=5, column=2)

f117 = Frame(root)
l3 = Label(f117, text = "Bush's presidency", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f117, text = "Republican George W. Bush served two terms as president, from 2001-2009.																								The September 11, 2001 terrorist attack led President Bush to reframe American foreign policy as a War on Terror, and to fight two wars in the Middle East.  																														A housing market crash led to a severe economic downturn in President Bush’s final years in office.", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f117, text=" Next ", command=notes_113)
btn2.grid(row=5, column=2)

f118 = Frame(root)
l3 = Label(f118,  image = pic63)
l3.grid(row = 3,column=2)
l4 = Label(f118, text = "Official White House portrait of Barack Obama, 44th president of the United States", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f118, text="Tell me more", command=notes_114)
btn2.grid(row=5, column=2)

f119 = Frame(root)
l3 = Label(f119, text = "The Obama Administration", font = ("Arial",13))
l3.grid(row = 3,column=2)
l4 = Label(f119, text = "Barack Obama was the 44th president of the United States and the first African American president in US history. He was elected in 2008 and served two terms. 																													Obama came into office during the worst economic crisis since the Great Depression and authorized a massive economic stimulus package that mitigated the worst effects of the crisis but substantially increased the federal debt and the federal budget deficit. 																									Though Obama’s presidential campaign was highly critical of the George W. Bush administration’s conduct in the War on Terror, once in office he pursued a similar approach to global terrorism.																											Obama’s signature domestic legislative achievement was the Patient Protection and Affordable Care Act, known colloquially as “Obamacare", font= ("Arial",13), wraplength = 400)
l4.grid(row = 4, column = 2)
btn2=Button(f119, text="We're done", command=notes_115)
btn2.grid(row=5, column=2)

f120 = Frame(root)
l3 = Label(f120,  image = pic64)
l3.grid(row = 3,column=2)
btn2=Button(f120, text="APUSH Done", command=notes_116)
btn2.grid(row=5, column=2)

f121 = Frame(root)
l3 = Label(f121,  image = pic65)
l3.grid(row = 3,column=2)
l4 = Label(f121, text = " Did I just cover the entire A.P. U.S. History syllabus in one sitting?", font = ('Arial', 13))
l4.grid(row=4, column =2)
l5 = Label(f121, text = " Well, let's see what I will get on the test tomorrow", font = ('Arial', 13))
l5.grid(row=5, column =2)
btn2=Button(f121, text="Go to bed", command=notes_117)
btn2.grid(row=6, column=2)

f122 = Frame(root)
l3 = Label(f122, image = pic66)
l3.grid(row = 3,column=2)
btn2=Button(f122, text="Time travel", command=notes_118)
btn2.grid(row=5, column=2)

f123 = Frame(root)
l3 = Label(f123,  image = pic67)
l3.grid(row = 3,column=2)
l4 = Label(f123, text = " Wow 5/5 on the APUSH test", font = ('Arial', 13))
l4.grid(row=4, column =2)
btn2=Button(f123, text="Resting time :)", command=notes_119)
btn2.grid(row=5, column=2)

f124 = Frame(root)
l3 = Label(f124, image = pic68)
l3.grid(row = 3,column=2)




root.mainloop()




#.grid(row = 3,column=2)